seed: 1235

mode: 'train'

# dataset:
#   train:
#     tfrecords: 'data/tf_example/training'
#     idxs: 'data/idxs_training_bs_1'
#   valid:
#     tfrecords: 'data/tf_example/validation'
#     idxs: 'data/idxs_validation_bs_1'
#   batchsize: 1

dataset:
  num_workers: 5
  train:
    tfrecords: 'data/tfrecords'
    idxs: 'data/idxs'
  valid:
    tfrecords: 'data/tfrecords'
    idxs: 'data/idxs'
  batchsize: 2

model:
  in_feature_dim: 9
  feature_dim: 256
  time_steps: 91
  in_dynamic_rg_dim: 3
  in_static_rg_dim: 6
  head_num: 4
  k: 4
  F: 6


device_ids: '0,1,2,3'
# device_num: 2

train:
  ckpt_path: ''
  accelerator: ''
  max_epochs: 100
  n_gpus: 1


