
seed: 20204333

n_gpus: [0]
model_type: 'BasicPMP'
mode: 'train'

dataset:
  type: 'waymo'
  waymo:
    num_workers: 5
    train:
      tfrecords: 'data/tfrecords'
      idxs: 'data/idxs'
    valid:
      tfrecords: 'data/tfrecords'
      idxs: 'data/idxs'
    batchsize: 10
  carla:
    root_dir: '/home/q10/ws/2021/naverlabs/scenario_generation/outputs/2021-07-20/13-30-09/saved_scenarios'
    batch_size: 24
    validation_split: 0.2
    shuffle_dataset: True
    num_workers: 10
  nuscenes:
    root_dir: '/dataset/nuscenes/dataset/v1.0-trainval_meta/'
    load_dir: '/dataset/nuscenes/parsed_for_pmp/'
    batch_size: 20
    validation_split: 0.2
    shuffle_dataset: True
    num_workers: 5

train:
  n_gpus: 1  # -1 for all, [gpu1, gpu2, ...] for specific
  accelerator: 'ddp'  # '' for None, 'dp', 'ddp'
  lr: 0.0001
  n_epochs: 100
  ckpt_path: ''  # for resume
  dirpath: ''
  verbose: True
  save_last: True
  save_top_k: 1
  monitor: 'val_f1'
  mode: 'max'
  early_stopping:
    active: True
    monitor: 'val_f1'
    mode: 'max'
    patience: 10
    verbose: True
    

test:
  ckpt_path: '/home/q10/ws/2021/naverlabs/probabilistic-map-prediction-for-SDV/outputs/2021-08-12/19-31-50/lightning_logs/version_0/checkpoints/epoch=14-val_loss=0.65-val_f1=0.53.ckpt'
  viz:
    is_active: True
    custom_destination: True
    viz_fps: 0.5
  






